### ISSUE TITLE
PHP8 issue with configs

### ISSUE THREAD

**Issue by mircobabini** [WPFreighter/wp-freighter#9] opened 2023-05-02 19:44 UTC
When there are no websites, the $stacked_mappings array is not defined. This is causing a fatal in wp-config.php. Tested in Local by Flywheel.

**Comment by austinginder** [comment] 2023-05-03 13:11
I was able to reproduce the issue on my end and I think the bug should be corrected with https://github.com/WPFreighter/wp-freighter/commit/3bb92bb476c5d7db83f57a239a7a2edde530909a. Mind giving it a try? Use the attached zip.

[wp-freighter.zip](https://github.com/WPFreighter/wp-freighter/files/11382841/wp-freighter.zip)

**Comment by mircobabini** [comment] 2023-05-03 13:49
Yep, the bug is related to in_array which wants an array as second param. But why not adding the array declaration as proposed in my PR? That fix is still necessary though, then thanks for adding it.

Your patch is working indeed.

**Comment by austinginder** [comment] 2023-05-03 14:14
I want to keep the code in wp-config.php as minimal as possible. The root issue seems to be due to the fact that it wasn't generating any `$stacked_mappings` at all, so I think my fix should take care of that. The other issue I believe is just PHP warning. I'm wondering if there is a way to wire in the domain mappings in a way that would be cleaner. A single liner doesn't seem sustainable when there are lots of sites. External file would be nice but also could be messy.

Might end up doing your suggestion however also need to make sure the cleaning of wp-config.php also handles removing a `$stacked_mappings = [];` declaration.

**Comment by mircobabini** [comment] 2023-05-03 14:20
> A single liner doesn't seem sustainable when there are lots of sites.
Agreed. But it's clean, at least.

> External file would be nice but also could be messy.
Yeah, same page. It's risky in case you don't have perms and so on.

> Need to make sure the cleaning of wp-config.php also handles removing a $stacked_mappings = []; declaration.
Not tested yet but it should work, by checking the cleanup code it's looking for the $stacked_mappings variable as one of the lines detector.

Thanks for sharing your thoughts.

**Comment by austinginder** [comment] 2023-05-03 14:22
Did some testing, should be good with https://github.com/WPFreighter/wp-freighter/commit/c5f483442f01878596fe46926015d139d948785d. Will includes these in the next release.

**Comment by austinginder** [comment] 2023-05-04 14:22
Fixed in https://github.com/WPFreighter/wp-freighter/releases/tag/v1.1.2. After updating I recommend re-saving WP Freighter configs in order to receive new configs.

**Closed by austinginder** 2023-05-04 14:22 UTC
